### ISSUE TITLE
Consider submitting a lightning talk to Code for All Summit

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#53]
Deadline July 31st.

https://form.typeform.com/to/NwzIwcie

**Comment by Ainali** [comment]
The tracks are: 

- Open vs. Closed Tech in Government
- Democracy & Elections
- Disinformation & Fake News
- Power Dynamics in Tech

The formats are:

- Panel
- Lightning talk
- Workshop

I think that a **lightning talk** in the **democracy** track would fit best for creating general awareness about Govdirectory.

Considering this is a Code for all summit, it might also be worth doing a workshop on some specific part, but I don't really know right now what that would be.

**Comment by Ainali** [comment]
Questions in the form:
- What is the title of your session? (in English)
- What is the goal of your session? This question is required.* (max. 100 words)
- Please describe your session (in English)This question is required. * (max. 250 words)
- How will you make sure your session is engaging? (e.g. whether you have 3 people or 30 people attend) This question is required.*
- What will participants get out of your session? This question is required.* (max. 100 words)
- How will you make sure your session is a safe space for all participants? This question is required.*
- What's your name and preferred pronouns? This question is required.*
- What's your email address?
- Institution/organization(s) you're part of
- In 2-5 lines, tell us a bit about you This question is required. *

**Comment by Abbe98** [comment]
Considering this is a Code for All call, maybe a lightning talk about using Wikidata as a data store and foundation for civic tech projects? With Govdirectory being an example?

**Comment by Ainali** [comment]
That is a great idea!

**Comment by Ainali** [comment]
First draft:
- What is the title of your session? (in English)
  - Wikidata in your CivicTech project
- What is the goal of your session? This question is required.* (max. 100 words)
  - The goal of this session is to explain how Wikidata can, and when it cannot, be used as a datastore and a foundation in a CivicTech project.
- Please describe your session (in English)This question is required. * (max. 250 words)
  - Using the tool Govdirectory as an example, we'll explain various ways of:
    - retrieving data from Wikidata
    - enrich Wikidata with facts you and others can reuse
    - explain trust systems and how you can use them 
  - We will also explain the basics of Wikidata, what it is for, how the community works and how you can be a part of the ecosystem.
- How will you make sure your session is engaging? (e.g. whether you have 3 people or 30 people attend) This question is required.*
  - We aim to give the participants concrete ideas of what they can build themselves, and perhaps how they can share data they already have. This should make this more than just a theoretical exercise and get their inspiriation going.
- What will participants get out of your session? This question is required.* (max. 100 words)
  - The participants will gain knowledge and inspiration. There is an entire community and ecosystem that wants to collaborate, so that the data that is being collected will get used by more people. This session is an invitation to that community.
- How will you make sure your session is a safe space for all participants? This question is required.*
- What's your name and preferred pronouns? This question is required.*
  - Albin Larsson, he/him
  - Jan Ainali, he/him
- What's your email address?
  - I'll enter this in the form
- Institution/organization(s) you're part of
  - None 
- In 2-5 lines, tell us a bit about you This question is required. *
  - Jan Ainali works at the Foundation for Public Code, helping public organizations collaborate on software development. Jan was the CEO of Wikimedia Sverige and has been a requirements analyst in software development.
  - Albin Larsson has a background working at publicly funded institutions, most recently at Europeana Foundation with R&D related to linked data and AI, Albin is now a freelancer who tries to work on open source and open data projects for a living. Albin has received several adwards and scholarships for his work relating to open data and startups.

**Comment by Abbe98** [comment]
Suggestions:


 - What is the goal of your session? This question is required.* (max. 100 words) 
The goal of this session is to explain how Wikipedia's sister-project Wikidata can, and when it cannot, be used as a datastore and backend in a CivicTech project. While also giving participants actionable skills and tools to experiment with Wikidata on their own.


- Please describe your session (in English)This question is required. * (max. 250 words) 
The session will start off by showcasing examples of existing CivicTech projects which use or have integrations with Wikidata.
Later the session will give participants usable examples of retrieving CivicTech-related data from Wikidata and visualizing it with Wikidata's Query Service. Going beyond that we will showcase how to edit Wikidata and expand the data relevant for one's project while also giving an introduction to the community and how it can help. Finally, we will explain and show Wikidata's trust system and take a critical look at the open-ended ecosystem and practices.

 - What will participants get out of your session? This question is required.* (max. 100 words)
The participants will gain knowledge and inspiration. There is an entire community and ecosystem that wants to collaborate so that the data that is being collected will get used by more people. This session is an invitation to that community. At the end of the session, participants will also have a set of practical data queries and tools at hand so that they can go straight into experimenting on their own.

**Comment by Ainali** [comment]
I like it! The only question left is "How will you make sure your session is a safe space for all participants?". I think that is hard to answer when we don't know which platform it is on and what tools it has to help with that.

**Comment by Abbe98** [comment]
"We will review and follow the conference's code of conduct(or similar documentation) and inform all participants about it and if possible we will moderate potential participant-generated such as chat messages if need be."

**Comment by Ainali** [comment]
This has been submitted. 🤞

**Comment by Ainali** [comment]
Just a note that the submission was accepted!
